services:
    app:
        build: .
        image: phuochungus/traffic_detection
        ports:
            - "3000:3000"
        environment:
            - SUPABASE_URL
            - SUPABASE_KEY
            - FIREBASE_CREDENTIALS
            - FIREBASE_API_KEY
            - NEO4J_URI
            - NEO4J_USERNAME
            - NEO4J_PASSWORD
