name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: nschloe/action-checkout-with-lfs-cache@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: install dependency
        run: |
          pip install -r app/requirements.txt
      - name: Run test
        run: pytest
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          FIREBASE_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}
          NEO4J_USERNAME: ${{secrets.NEO4J_USERNAME}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          AURA_INSTANCEID: ${{secrets.AURA_INSTANCEID}}
          AURA_INSTANCENAME: ${{secrets.AURA_INSTANCENAME}}
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
