name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-unbuntu:
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ "3.8", "3.10", "3.9"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r app/requirements.txt
      - name: Run test
        run: pytest
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          FIREBASE_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}
          NEO4J_USERNAME: ${{secrets.NEO4J_USERNAME}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          AURA_INSTANCEID: ${{secrets.AURA_INSTANCEID}}
          AURA_INSTANCENAME: ${{secrets.AURA_INSTANCENAME}}
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      - name: Run mutation test
        run: mutatest
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          FIREBASE_CREDENTIALS: ${{secrets.FIREBASE_CREDENTIALS}}
          NEO4J_URI: ${{secrets.NEO4J_URI}}
          NEO4J_USERNAME: ${{secrets.NEO4J_USERNAME}}
          NEO4J_PASSWORD: ${{secrets.NEO4J_PASSWORD}}
          AURA_INSTANCEID: ${{secrets.AURA_INSTANCEID}}
          AURA_INSTANCENAME: ${{secrets.AURA_INSTANCENAME}}
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
